services:
  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    container_name: datagusto-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-datagusto}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - datagusto-network

  # Database migration service
  backend-migrations:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: datagusto-migrations
    volumes:
      - ./backend/alembic:/app/alembic
      - ./backend/alembic.ini:/app/alembic.ini
    working_dir: /app
    command: ["sh", "-c", "PYTHONPATH=/app alembic upgrade head"]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database configuration (required by config.py)
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-datagusto}
    networks:
      - datagusto-network

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: datagusto-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      backend-migrations:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy
    environment:
      # Database configuration (required by config.py)
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-datagusto}

      # JWT configuration (required by config.py)
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_REFRESH_SECRET_KEY: ${JWT_REFRESH_SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      JWT_REFRESH_TOKEN_EXPIRE_DAYS: ${JWT_REFRESH_TOKEN_EXPIRE_DAYS:-7}
      ALGORITHM: ${ALGORITHM:-HS256}

      # LLM configuration (optional)
      LLM_PROVIDER: ${LLM_PROVIDER:-}
      LLM_MODEL: ${LLM_MODEL:-}
      LLM_API_KEY: ${LLM_API_KEY:-}
      LLM_ENDPOINT: ${LLM_ENDPOINT:-}

      # Application configuration
      PROJECT_NAME: ${PROJECT_NAME:-DataGusto Platform API}
      API_V1_STR: ${API_V1_STR:-/api}
      ENVIRONMENT: ${ENVIRONMENT:-development}
      ENABLE_REGISTRATION: ${ENABLE_REGISTRATION:-true}
      DEBUG: ${DEBUG:-false}

      # Python configuration
      PYTHONUNBUFFERED: 1
    networks:
      - datagusto-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
        NEXT_PUBLIC_API_VERSION: ${NEXT_PUBLIC_API_VERSION:-v1}
    container_name: datagusto-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      NEXT_PUBLIC_API_VERSION: ${NEXT_PUBLIC_API_VERSION:-v1}
      NODE_ENV: production
      NEXT_PUBLIC_DISABLE_DEVTOOLS: "true"
    networks:
      - datagusto-network

volumes:
  postgres_data:
    driver: local

networks:
  datagusto-network:
    driver: bridge
