"""Remove current_organization_id from User model

Revision ID: 37b8c1fc5567
Revises: 31be7037d1fd
Create Date: 2025-06-10 23:41:29.829278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37b8c1fc5567'
down_revision: Union[str, None] = '31be7037d1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_current_organization_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'current_organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_current_organization_id_fkey', 'users', 'organizations', ['current_organization_id'], ['id'])
    # ### end Alembic commands ###
