"""add_tool_definition_and_revision_tables

Revision ID: 3b888e0f3f74
Revises: 5f4880c2a5ea
Create Date: 2025-11-18 16:19:54.725776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b888e0f3f74'
down_revision: Union[str, None] = '5f4880c2a5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_definition_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent this revision belongs to'),
    sa.Column('tools_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB containing tool definitions array'),
    sa.Column('previous_revision_id', sa.UUID(), nullable=True, comment='Previous revision in history chain (NULL = first revision)'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created this revision (audit trail)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_revision_id'], ['tool_definition_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('tool_definition_revisions_agent_id_idx', 'tool_definition_revisions', ['agent_id'], unique=False)
    op.create_index('tool_definition_revisions_created_at_idx', 'tool_definition_revisions', ['created_at'], unique=False)
    op.create_index('tool_definition_revisions_previous_revision_id_idx', 'tool_definition_revisions', ['previous_revision_id'], unique=False)
    op.create_index('tool_definition_revisions_tools_data_gin_idx', 'tool_definition_revisions', ['tools_data'], unique=False, postgresql_using='gin')
    op.create_table('tool_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent this tool definition belongs to (unique)'),
    sa.Column('latest_revision_id', sa.UUID(), nullable=True, comment='Current active revision (NULL until first revision created)'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the tool definition (audit trail)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['latest_revision_id'], ['tool_definition_revisions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_index('tool_definitions_agent_id_idx', 'tool_definitions', ['agent_id'], unique=True)
    op.create_index('tool_definitions_latest_revision_id_idx', 'tool_definitions', ['latest_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('tool_definitions_latest_revision_id_idx', table_name='tool_definitions')
    op.drop_index('tool_definitions_agent_id_idx', table_name='tool_definitions')
    op.drop_table('tool_definitions')
    op.drop_index('tool_definition_revisions_tools_data_gin_idx', table_name='tool_definition_revisions', postgresql_using='gin')
    op.drop_index('tool_definition_revisions_previous_revision_id_idx', table_name='tool_definition_revisions')
    op.drop_index('tool_definition_revisions_created_at_idx', table_name='tool_definition_revisions')
    op.drop_index('tool_definition_revisions_agent_id_idx', table_name='tool_definition_revisions')
    op.drop_table('tool_definition_revisions')
    # ### end Alembic commands ###
