"""add_guardrail_tables

Revision ID: 5e808e8ad2f5
Revises: 94177671ff04
Create Date: 2025-09-30 23:27:34.527269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e808e8ad2f5'
down_revision: Union[str, None] = '94177671ff04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project this guardrail belongs to'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization (denormalized from project for RLS)'),
    sa.Column('name', sa.Text(), nullable=False, comment='Guardrail display name'),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB containing trigger conditions and actions'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the guardrail'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('guardrails_definition_gin_idx', 'guardrails', ['definition'], unique=False, postgresql_using='gin')
    op.create_index('guardrails_name_idx', 'guardrails', ['name'], unique=False)
    op.create_index('guardrails_organization_id_idx', 'guardrails', ['organization_id'], unique=False)
    op.create_index('guardrails_project_id_idx', 'guardrails', ['project_id'], unique=False)
    op.create_index('guardrails_project_name_idx', 'guardrails', ['project_id', 'name'], unique=False)
    op.create_table('guardrail_active_status',
    sa.Column('guardrail_id', sa.UUID(), nullable=False, comment='Guardrail ID (also primary key)'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['guardrail_id'], ['guardrails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guardrail_id')
    )
    op.create_table('guardrail_agent_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project (denormalized for RLS)'),
    sa.Column('guardrail_id', sa.UUID(), nullable=False, comment='Guardrail ID'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent ID'),
    sa.Column('assigned_by', sa.UUID(), nullable=False, comment='User who made the assignment'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardrail_id'], ['guardrails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardrail_id', 'agent_id', name='guardrail_agent_assignments_unique')
    )
    op.create_index('guardrail_agent_assignments_agent_id_idx', 'guardrail_agent_assignments', ['agent_id'], unique=False)
    op.create_index('guardrail_agent_assignments_assigned_by_idx', 'guardrail_agent_assignments', ['assigned_by'], unique=False)
    op.create_index('guardrail_agent_assignments_guardrail_id_idx', 'guardrail_agent_assignments', ['guardrail_id'], unique=False)
    op.create_index('guardrail_agent_assignments_project_id_idx', 'guardrail_agent_assignments', ['project_id'], unique=False)
    op.create_table('guardrail_archives',
    sa.Column('guardrail_id', sa.UUID(), nullable=False, comment='Archived guardrail ID (also primary key)'),
    sa.Column('reason', sa.Text(), nullable=False, comment='Reason for archiving (audit trail)'),
    sa.Column('archived_by', sa.UUID(), nullable=False, comment='User who performed the archiving'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guardrail_id'], ['guardrails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guardrail_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardrail_archives')
    op.drop_index('guardrail_agent_assignments_project_id_idx', table_name='guardrail_agent_assignments')
    op.drop_index('guardrail_agent_assignments_guardrail_id_idx', table_name='guardrail_agent_assignments')
    op.drop_index('guardrail_agent_assignments_assigned_by_idx', table_name='guardrail_agent_assignments')
    op.drop_index('guardrail_agent_assignments_agent_id_idx', table_name='guardrail_agent_assignments')
    op.drop_table('guardrail_agent_assignments')
    op.drop_table('guardrail_active_status')
    op.drop_index('guardrails_project_name_idx', table_name='guardrails')
    op.drop_index('guardrails_project_id_idx', table_name='guardrails')
    op.drop_index('guardrails_organization_id_idx', table_name='guardrails')
    op.drop_index('guardrails_name_idx', table_name='guardrails')
    op.drop_index('guardrails_definition_gin_idx', table_name='guardrails', postgresql_using='gin')
    op.drop_table('guardrails')
    # ### end Alembic commands ###
