"""drop_user_suspensions_table

Revision ID: 5f4880c2a5ea
Revises: c3706f5fffe8
Create Date: 2025-10-08 13:56:21.753838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f4880c2a5ea'
down_revision: Union[str, None] = 'c3706f5fffe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_suspensions_user_id_idx', table_name='user_suspensions')
    op.drop_table('user_suspensions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_suspensions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='Unique suspension record ID'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Suspended user ID'),
    sa.Column('suspended_until', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='End date for temporary suspension (NULL = indefinite)'),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False, comment='Reason for suspension (audit trail)'),
    sa.Column('suspended_by', sa.UUID(), autoincrement=False, nullable=False, comment='User who performed the suspension'),
    sa.Column('lifted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='When suspension was lifted (NULL = still suspended)'),
    sa.Column('lifted_by', sa.UUID(), autoincrement=False, nullable=True, comment='User who lifted the suspension'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['lifted_by'], ['users.id'], name='user_suspensions_lifted_by_fkey'),
    sa.ForeignKeyConstraint(['suspended_by'], ['users.id'], name='user_suspensions_suspended_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_suspensions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_suspensions_pkey')
    )
    op.create_index('user_suspensions_user_id_idx', 'user_suspensions', ['user_id'], unique=False)
    # ### end Alembic commands ###
