"""Add run_id to observations

Revision ID: cbf7b11e29b5
Revises: e34b1360c985
Create Date: 2025-03-25 18:11:49.625747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf7b11e29b5'
down_revision: Union[str, None] = 'e34b1360c985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('run_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_observations_run_id'), 'observations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_run_id'), table_name='observations')
    op.drop_column('observations', 'run_id')
    # ### end Alembic commands ###
