"""add_past_instructions_and_previous_extraction_to_session_alignment_history

Revision ID: d08f3fb47e70
Revises: eb131cdc2c70
Create Date: 2025-11-26 07:41:46.780655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd08f3fb47e70'
down_revision: Union[str, None] = 'eb131cdc2c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_alignment_history', sa.Column('past_instructions_history', sa.Text(), nullable=True, comment='Past instructions history (for context in key term extraction)'))
    op.add_column('session_alignment_history', sa.Column('previous_extraction_output', sa.Text(), nullable=True, comment='Previous extraction output (for iterative key term extraction)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_alignment_history', 'previous_extraction_output')
    op.drop_column('session_alignment_history', 'past_instructions_history')
    # ### end Alembic commands ###
