"""remove created_by from sessions

Revision ID: d212f974c4b0
Revises: 6418537daf9b
Create Date: 2025-11-27 10:18:05.024074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd212f974c4b0'
down_revision: Union[str, None] = '6418537daf9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('session_alignment_history_created_by_fkey', 'session_alignment_history', type_='foreignkey')
    op.drop_column('session_alignment_history', 'created_by')
    op.drop_index('sessions_created_by_idx', table_name='sessions')
    op.drop_constraint('sessions_created_by_fkey', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False, comment='User who created the session'))
    op.create_foreign_key('sessions_created_by_fkey', 'sessions', 'users', ['created_by'], ['id'])
    op.create_index('sessions_created_by_idx', 'sessions', ['created_by'], unique=False)
    op.add_column('session_alignment_history', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False, comment='User who performed the alignment'))
    op.create_foreign_key('session_alignment_history_created_by_fkey', 'session_alignment_history', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
