"""add session validation log table

Revision ID: d2b1e36354cf
Revises: d08f3fb47e70
Create Date: 2025-11-26 14:04:29.748695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2b1e36354cf'
down_revision: Union[str, None] = 'd08f3fb47e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_validation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Session that contains the guardrails'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent that made the validation request'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project the agent belongs to'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization (denormalized for RLS)'),
    sa.Column('trace_id', sa.Text(), nullable=True, comment='Optional trace ID from external tracing system'),
    sa.Column('log_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB containing validation details'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('session_validation_logs_agent_id_idx', 'session_validation_logs', ['agent_id'], unique=False)
    op.create_index('session_validation_logs_created_at_idx', 'session_validation_logs', ['created_at'], unique=False)
    op.create_index('session_validation_logs_log_data_gin_idx', 'session_validation_logs', ['log_data'], unique=False, postgresql_using='gin')
    op.create_index('session_validation_logs_organization_id_idx', 'session_validation_logs', ['organization_id'], unique=False)
    op.create_index('session_validation_logs_project_id_idx', 'session_validation_logs', ['project_id'], unique=False)
    op.create_index('session_validation_logs_session_id_idx', 'session_validation_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('session_validation_logs_session_id_idx', table_name='session_validation_logs')
    op.drop_index('session_validation_logs_project_id_idx', table_name='session_validation_logs')
    op.drop_index('session_validation_logs_organization_id_idx', table_name='session_validation_logs')
    op.drop_index('session_validation_logs_log_data_gin_idx', table_name='session_validation_logs', postgresql_using='gin')
    op.drop_index('session_validation_logs_created_at_idx', table_name='session_validation_logs')
    op.drop_index('session_validation_logs_agent_id_idx', table_name='session_validation_logs')
    op.drop_table('session_validation_logs')
    # ### end Alembic commands ###
