"""remove_user_organization_id

Revision ID: d6b1246973c1
Revises: 88b4cca42035
Create Date: 2025-09-30 22:12:46.136211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6b1246973c1'
down_revision: Union[str, None] = '88b4cca42035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_organization_id_idx', table_name='users')
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False, comment='Organization the user belongs to'))
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_index('users_organization_id_idx', 'users', ['organization_id'], unique=False)
    # ### end Alembic commands ###
