"""add_session_and_alignment_history_tables

Revision ID: eb131cdc2c70
Revises: 3b888e0f3f74
Create Date: 2025-11-26 07:13:16.267134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb131cdc2c70'
down_revision: Union[str, None] = '3b888e0f3f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent this session belongs to'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Project (denormalized from agent for RLS)'),
    sa.Column('organization_id', sa.UUID(), nullable=False, comment='Organization (denormalized from agent for RLS)'),
    sa.Column('status', sa.Text(), nullable=False, comment='Session lifecycle status (active, completed, expired)'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who created the session'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('sessions_agent_id_idx', 'sessions', ['agent_id'], unique=False)
    op.create_index('sessions_agent_status_idx', 'sessions', ['agent_id', 'status'], unique=False)
    op.create_index('sessions_created_at_idx', 'sessions', ['created_at'], unique=False)
    op.create_index('sessions_created_by_idx', 'sessions', ['created_by'], unique=False)
    op.create_index('sessions_organization_id_idx', 'sessions', ['organization_id'], unique=False)
    op.create_index('sessions_project_id_idx', 'sessions', ['project_id'], unique=False)
    op.create_index('sessions_status_idx', 'sessions', ['status'], unique=False)
    op.create_table('session_alignment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False, comment='Session this alignment belongs to'),
    sa.Column('agent_id', sa.UUID(), nullable=False, comment='Agent (denormalized for fast queries)'),
    sa.Column('user_instruction', sa.Text(), nullable=False, comment='User instruction for this alignment iteration'),
    sa.Column('alignment_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='JSONB containing alignment data (key_terms, tool_invocation_rules)'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='User who performed the alignment'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('session_alignment_history_agent_id_idx', 'session_alignment_history', ['agent_id'], unique=False)
    op.create_index('session_alignment_history_alignment_result_gin_idx', 'session_alignment_history', ['alignment_result'], unique=False, postgresql_using='gin')
    op.create_index('session_alignment_history_created_at_idx', 'session_alignment_history', ['created_at'], unique=False)
    op.create_index('session_alignment_history_session_created_at_idx', 'session_alignment_history', ['session_id', 'created_at'], unique=False)
    op.create_index('session_alignment_history_session_id_idx', 'session_alignment_history', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('session_alignment_history_session_id_idx', table_name='session_alignment_history')
    op.drop_index('session_alignment_history_session_created_at_idx', table_name='session_alignment_history')
    op.drop_index('session_alignment_history_created_at_idx', table_name='session_alignment_history')
    op.drop_index('session_alignment_history_alignment_result_gin_idx', table_name='session_alignment_history', postgresql_using='gin')
    op.drop_index('session_alignment_history_agent_id_idx', table_name='session_alignment_history')
    op.drop_table('session_alignment_history')
    op.drop_index('sessions_status_idx', table_name='sessions')
    op.drop_index('sessions_project_id_idx', table_name='sessions')
    op.drop_index('sessions_organization_id_idx', table_name='sessions')
    op.drop_index('sessions_created_by_idx', table_name='sessions')
    op.drop_index('sessions_created_at_idx', table_name='sessions')
    op.drop_index('sessions_agent_status_idx', table_name='sessions')
    op.drop_index('sessions_agent_id_idx', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
